#!/bin/sh
#
# Git archive extraction pre commit hook
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
# License: CC-BY-4.0
# Version: 1.0.2

# Configuration
ARCHIVE_EXTENSIONS=$(cat .gitattributes | grep "zip" | tr -d [][:upper:] | cut -d " " -f1 | cut -d. -f2 | head -c -1 | tr "\n" "|")

# Processing
for STAGED_FILE in $(git diff --name-only --cached | grep -iE "\.($ARCHIVE_EXTENSIONS)$")
do
	# Deletes the old archive content
	rm -rf ".$(basename $STAGED_FILE).content"
	# Extracts the archive content, if the archive itself is not removed
	if [ -f "$STAGED_FILE" ]; then
		unzip -o $STAGED_FILE -d "$(dirname $STAGED_FILE)/.$(basename $STAGED_FILE).content"
	fi
	# Adds extracted or deleted archive content to the stage
	git add "$(dirname $STAGED_FILE)/.$(basename $STAGED_FILE).content"
done
